--!strict

local Types = require(script.Parent.Types)

local State = {}

State.nextZoneId = 1
State.nextGroupId = 1
State.nextCollectionId = 1

State.collections = {} :: { [number]: Types.Collection }
State.itemToCollection = {} :: { [Types.Item]: number }
State.collectionToGroups = {} :: { [number]: { [number]: boolean } }

State.objects = {} :: { Types.BoundingVolume }
State.rootNode = nil :: Types.Node?
State.pendingRebuild = false
State.isDirty = false

State.groupTrackingItems = {} :: { [number]: { [Types.Item]: boolean } }
State.groupPriorityMap = {} :: { [number]: number }
State.itemCustomData = {} :: { [Types.Item]: { [number]: any } }
State.groupEnteredCallbacks = {} :: { [number]: { Types.Callback } }
State.groupExitedCallbacks = {} :: { [number]: { Types.Callback } }

State.zoneBoundGroups = {} :: { [number]: { number } }
State.zoneIndexToZoneObj = {} :: { [number]: Types.Zone }
State.groupUIDToGroupObj = {} :: { [number]: Types.Group }

return State
